name: ci-cd-pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: install dependencies
        run: make install-ci
      - name: run linter
        run: make lint
      - name: run tests
        run: make test
